name: my second workflow
on: workflow_dispatch
jobs:
    event-info-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Trigger event
              run: echo "My Trigger event is ${{ github.event_name }} event"